app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults:
        _controller: nelmio_api_doc.controller.swagger_ui
app.swagger:
    path: /api/doc.{_format}
    methods: GET
    defaults:
        _controller: nelmio_api_doc.controller.swagger
        area: 'default'
        _format: json
    requirements:
        _format: json|yaml
